

clean:
	rm  -rf  ./scenario-server/__pycache__
	rm  -rf  ./scenario-server/src/scenario_server/__pycache__
	rm  -rf  ./scenario-server/src/scenario_server/handlers/__pycache__
	rm  -rf  ./scenario-server/src/scenario_server/handlers/aob/__pycache__
	rm  -rf  ./scenario-server/src/scenario_server/handlers/aob_iot/__pycache__
	rm  -rf  ./scenario-server/src/scenario_server/handlers/aob_tsfm/__pycache__
	rm  -rf  ./scenario-server/src/scenario_server/handlers/aob_workorders/__pycache__
	rm  -rf  ./src/scenario-server/__pycache__


local:
	uv  sync  --refresh  --reinstall
