FROM docker.io/postgres:17.6
COPY data/ /tmp
COPY 01_eamlite.sql /docker-entrypoint-initdb.d/
COPY 02_etl_wo.sql /docker-entrypoint-initdb.d/
COPY 03_etl_ts.sql /docker-entrypoint-initdb.d/
COPY 04_etl_siteloc.sql /docker-entrypoint-initdb.d/
